[package]
name = "objectsDAO"
version = "1.0.0"
authors = []

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"


[addresses]
objectsDAO = "0x0"
